name: 'Merge release branch into Dev branch'
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo `git ls-remote git@github.com:hagel86/action_testing.git | grep "/branch-release-" | sed 's?.*refs/heads/??' | tail -1`)"
      id: release_branch
    - name: Checkout
      uses: actions/checkout@v1
    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.0.3
      with:
        stable_branch: ${{ steps.release_branch.outputs.branch }}
        development_branch: 'master'
        allow_ff: false
        user_name: prism-builds
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      