- name: Extract branch name
    shell: bash
    run: echo "##[set-output name=branch;]$(echo `git ls-remote --heads | grep "/branch-release-" | sed 's?.*refs/heads/??' | tail -1`)"
    id: release_branch

- name: 'Merge Release into Dev'

  on:
    push:
      branches:
        - ${{ steps.release_branch.outputs.branch }}

  jobs:
    nightly-merge:

      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Nightly Merge
        uses: robotology/gh-action-nightly-merge@v1.0.3
        with:
          stable_branch: ${{ steps.release_branch.outputs.branch }}
          development_branch: 'master'
          allow_ff: false
          user_name: prism-builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
